---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 36000
- name: Remove old docker versions if present
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Install docker prerequisites and system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - gnupg
      - lsb-release
      - python3-setuptools
    state: latest
