---
- name: Play needed tasks in order
  ansible.builtin.include_tasks: "{{ files }}"
  with_items:
    - docker-prerequisites.yaml
    - docker-install.yaml
    - file-copy.yaml
  loop_control:
    loop_var: files
