# This is the ansible inventory file which contains host variables and targets for other ansible resources in this repository
# https://docs.ansible.com/projects/ansible/latest/inventory_guide/intro_inventory.html

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu

[linux]
# example entries below
# hostname ansible_host=hostname.example.com
# hostname2 ansible_host=123.123.123.123