[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
ansible_user=azureuser
ca2-vm ansible_host=4.233.141.17 


[CA2]
ca2-vm ansible_host=4.233.141.17 